

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;

@Path("/webgen")

public class WebGen {
	
private static Map<String, Gen> genes = new HashMap<String, Gen>();
	
	static {
		
		Gen gen1 = new Gen();
		gen1.setId("TP53");
		gen1.setName("P53 Tumor Suppressor");
		gen1.setOrganism("Homo sapiens");
		gen1.setStartPos("Chr17:7512445");
		gen1.setEndPos("Chr17:7531642");
		gen1.setSequence("GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTC"
				+ "TAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTG"
				+ "\nCTTTCCACGACGGTGACACGCTTCCCTGGATTGGGTAAGCTCCTGACTGAACTTGATGAGTCCTCTCTGA"
				+ "GTCACGGGCTCTCGGCTCCGTGTATTTTCAGCTCGGGAAAATCGCTGGGGCTGGGGGTGGGGCAGTGGGG"
				+ "\nACTTAGCGAGTTTGGGGGTGAGTGGGATGGAAGCTTGGCTAGAGGGATCATCATAGGAGTTGCATTGTTG"
				+ "GGAGACCTGGGTGTAGATGATGGGGATGTTAGGACCATCCGAACTCAAAGTTGAACGCCTAGGCAGAGGA"
				+ "\nGTGGAGCTTTGGGGAACCTTGAGCCGGCCTAAAGCGTACTTCTTTGCACATCCACCCGGTGCTGGGCGTA"
				+ "GGGAATCCCTGAAATAAAAGATGCACAAAGCATTGAGGTCTGAGACTTTTGGATCTCGAAACATTGAGAA"
				+ "\nCTCATAGCTGTATATTTTAGAGCCCATGGCATCCTAGTGAAAACTGGGGCTCCATTCCGAAATGATCATT"
				+ "TGGGGGTGATCCGGGGAGCCCAAGCTGCTAAGGTCCCACAACTTCCGGACCTTTGTCCTTCCTGGAGCGA"
				+ "\nTCTTTCCAGGCAGCCCCCGGCTCCGCTAGATGGAGAAAATCCAATTGAAGGCTGTCAGTCGTGGAAGTGA"
				+ "GAAGTGCTAAACCAGGGGTTTGCCCGCCAGGCCGAGGAGGACCGTCGCAATCTGAGAGGCCCGGCAGCCC"
				+ "\nTGTTATTGTTTGGCTCCACATTTACATTTCTGCCTCTTGCAGCAGCATTTCCGGTTTCTTTTTGCCGGAG"
				+ "CAGCTCACTATTCACCCGATGAGAGGGGAGGAGAGAGAGAGAAAATGTCCTTTAGGCCGGTTCCTCTTAC"
				+ "\nTTGGCAGAGGGAGGCTGCTATTCTCCGCCTGCATTTCTTTTTCTGGATTACTTAGTTATGGCCTTTGCAA"
				+ "AGGCAGGGGTATTTGTTTTGATGCAAACCTCAATCCCTCCCCTTCTTTGAATGGTGTGCCCCACCCCGCG"
				+ "\nGGTCGCCTGCAACCTAGGCGGACGCTACCATGGCGTGAGACAGGGAGGGAAAGAAGTGTGCAGAAGGCAA"
				+ "GCCCGGAGGTATTTTCAAGAATGAGTATATCTCATCTTCCCGGAGGAAAAAAAAAAAGAATGGGTACGTC"
				+ "\nTGAGAATCAAATTTTGAAAGAGTGCAATGATGGGTCGTTTGATAATTTGTCGGAAAAACAATCTACCTGT"
				+ "TATCTAGCTTTGGGCTAGGCCATTCCAGTTCCAGACGCAGGCTGAACGTCGTGAAGCGGAAGGGGCGGGC"
				+ "\nCCGCAGGCGTCCGTGTGGTCCTCCGTGCAGCCCTCCGGCCCGAGCCGGTTCTTCCTGGTAGGAGGCGGAA"
				+ "CTCGAATTCATTTCTCCCGCTGCCCCATCTCTTAGCTCGCGGTTGTTTCATTCCGCAGTTTCTTCCCATG"
				+ "\nCACCTGCCGCGTACCGGCCACTTTGTGCCGTACTTACGTCATCTTTTTCCTAAATCGAGGTGGCATTTAC"
				+ "ACACAGCGCCAGTGCACACAGCAAGTGCACAGGAAGATGAGTTTTGGCCCCTAACCGCTCCGTGATGCCT");
		genes.put(gen1.getId(), gen1);
		
		Gen gen2 = new Gen();
		gen2.setId("BRCA1");
		gen2.setName("BRCA1, DNA repair associated");
		gen2.setOrganism("Homo sapiens");
		gen2.setStartPos("Chr17:43044295");
		gen2.setEndPos("Chr17:43170245");
		gen2.setSequence("GTACCTTGATTTCGTATTCTGAGAGGCTGCTGCTTAGCGGTAGCCCCTTGGTTTCCGTGGCAACGGAAAA"
				+ "GCGCGGGAATTACAGATAAATTAAAACTGCGACTGCGCGGCGTGAGCTCGCTGAGACTTCCTGGACGGGG"
				+ "\nGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGCCTTCACCCTCTGCTCTGGGTA"
				+ "AAGGTAGTAGAGTCCCGGGAAAGGGACAGGGGGCCCAAGTGATGCTCTGGGGTACTGGCGTGGGAGAGTG"
				+ "\nGATTTCCGAAGCTGACAGATGGGTATTCTTTGACGGGGGGTAGGGGCGGAACCTGAGAGGCGTAAGGCGT"
				+ "TGTGAACCCTGGGGAGGGGGGCAGTTTGTAGGTCGCGAGGGAAGCGCTGAGGATCAGGAAGGGGGCACTG"
				+ "\nAGTGTCCGTGGGGGAATCCTCGTGATAGGAACTGGAATATGCCTTGAGGGGGACACTATGTCTTTAAAAA"
				+ "CGTCGGCTGGTCATGAGGTCAGGAGTTCCAGACCAGCCTGACCAACGTGGTGAAACTCCGTCTCTACTAA"
				+ "\nAAATACAAAAATTAGCCGGGCGTGGTGCCGCTCCAGCTACTCAGGAGGCTGAGGCAGGAGAATCGCTAGA"
				+ "ACCCGGGAGGCGGAGGTTGCAGTGAGCCGAGATCGCGCCATTGCACTCCAGCCTGGGCGACAGAGCGAGA"
				+ "\nCTGTCTCAAAACAAAACAAAACAAAACAAAACAAAAAACACCGGCTGGTATGTATGAGAGGATGGGACCT"
				+ "TGTGGAAGAAGAGGTGCCAGGAATATGTCTGGGAAGGGGAGGAGACAGGATTTTGTGGGAGGGAGAACTT"
				+ "\nAAGAACTGGATCCATTTGCGCCATTGAGAAAGCGCAAGAGGGAAGTAGAGGAGCGTCAGTAGTAACAGAT"
				+ "GCTGCCGGCAGGGATGTGCTTGAGGAGGATCCAGAGATGAGAGCAGGTCACTGGGAAAGGTTAGGGGCGG"
				+ "\nGGAGGCCTTGATTGGTGTTGGTTTGGTCGTTGTTGATTTTGGTTTTATGCAAGAAAAAGAAAACAACCAG"
				+ "AAACATTGGAGAAAGCTAAGGCTACCACCACCTACCCGGTCAGTCACTCCTCTGTAGCTTTCTCTTTCTT"
				+ "\nGGAGAAAGGAAAAGACCCAAGGGGTTGGCAGCAATATGTGAAAAAATTCAGAATTTATGTTGTCTAATTA"
				+ "CAAAAAGCAACTTCTAGAATCTTTAAAAATAAAGGACGTTGTCATTAGTTCTTTGGTTTGTATTATTCTA"
				+ "\nAAACCTTCCAAATCTTAAATTTACTTTATTTTAAAATGATAAAATGAAGTTGTCATTTTATAAACCTTTT"
				+ "AAAAAGATATATATATATGTTTTTCTAATGTGTTAAAGTTCATTGGAACAGAAAGAAATGGATTTATCTG"
				+ "\nCTCTTCGCGTTGAAGAAGTACAAAATGTCATTAATGCTATGCAGAAAATCTTAGAGTGTCCCATCTGGTA"
				+ "AGTCAGCACAAGAGTGTATTAATTTGGGATTCCTATGATTATCTCCTATGCAAATGAACAGAATTGACCT"
				+ "\nTACATACTAGGGAAGAAAAGACATGTCTAGTAAGATTAGGCTATTGTAATTGCTGATTTTCTTAACTGAA"
				+ "GAACTTTAAAAATATAGAAAATGATTCCTTGTTCTCCATCCACTCTGCCTCTCCCACTCCTCTCCTTTTC");
		genes.put(gen2.getId(), gen2);
		
	}
	
	@GET
	@Path("/hello")
	@Produces("text/plain")
	public String hello() {
		return "Hello World!!! Guille";
	}
	
	@GET
	@Path("/message/{message}")
	@Produces("text/plain")
	public String showMsg(@PathParam("message") String message) {
		return message;
	}
	
	@GET
	@Path("/genes")
	@Produces("text/xml")
	public List<Gen> listGenes() {
		return new ArrayList<Gen>(genes.values());
	}
	
	@GET
	@Path("/genes/id/{id}")
	@Produces("text/xml")
	public Gen listGenesID(@PathParam("id") String id) {
		return genes.get(id);
	}
	
	@GET
	@Path("/json/genes")
	@Produces("application/json")
	public List<Gen> listGenesJSON() {
		return new ArrayList<Gen>(genes.values());
	}
	
	@GET
	@Path("/json/genes/id/{id}")
	@Produces("application/json")
	public Gen listGenesJSONID(@PathParam("id") String id) {
		return genes.get(id);
	}

}
